### PR TITLE
Judge youhai

### PR DESCRIPTION
**Pull request by Altair59**
Judge and Speaker sections 99% finished.
TODO:
1. Shannon Mclean picture still not received from PR, cannot post her image.
2. Theme color adjustment.

### CODE REVIEW

**Comment by Falanke21** [comment]
Will look more into it tonight

**Comment by Falanke21** [comment]
Also, for index.html, it seems like you formatted the whole document. You probably don't want to do that here since everyone else might run into a merge conflict later. Only format the part you changed if possible @Altair59 . Thanks!

**Comment by Altair59** [comment]
> 
> 
> Also, for index.html, it seems like you formatted the whole document. You probably don't want to do that here since everyone else might run into a merge conflict later. Only format the part you changed if possible @Altair59 . Thanks!

Canceled auto-format for other parts in index.html

**Comment by Falanke21** [comment]
good work!

**Pull request merged**
